import React, { useState } from 'react';
import { Copy, Check, Terminal, FileText } from 'lucide-react';
import { TcpParams } from '../types';

interface Props {
  params: TcpParams;
  variant: 'file' | 'command';
}

const SysctlOutput: React.FC<Props> = ({ params, variant }) => {
  const [copied, setCopied] = useState(false);

  let content = '';
  let title = '';
  let Icon = FileText;

  if (variant === 'file') {
    title = '/etc/sysctl.d/99-tcp-tuning.conf';
    Icon = FileText;
    content = `
# TCP Tuning Parameters
# Generated by TCP TuneAI
# BDP: ${params.bdpBytes} bytes

net.core.rmem_max=${params.rmemMax}
net.core.wmem_max=${params.wmemMax}
net.ipv4.tcp_rmem=${params.tcpRmem.join(' ')}
net.ipv4.tcp_wmem=${params.tcpWmem.join(' ')}
`.trim();
  } else {
    title = 'Terminal / Shell (Runtime)';
    Icon = Terminal;
    // Note: wrapping array values in quotes for shell safety
    content = `
sysctl -w net.core.rmem_max=${params.rmemMax}
sysctl -w net.core.wmem_max=${params.wmemMax}
sysctl -w net.ipv4.tcp_rmem="${params.tcpRmem.join(' ')}"
sysctl -w net.ipv4.tcp_wmem="${params.tcpWmem.join(' ')}"
`.trim();
  }

  const handleCopy = () => {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="bg-slate-900 rounded-lg border border-slate-700 shadow-xl overflow-hidden mt-4 first:mt-0">
      <div className="flex items-center justify-between px-4 py-2 bg-slate-800 border-b border-slate-700">
        <div className="flex items-center gap-2">
          <Icon size={14} className="text-slate-400" />
          <span className="text-xs font-mono text-slate-400">{title}</span>
        </div>
        <button
          onClick={handleCopy}
          className="flex items-center gap-1 text-xs font-medium text-blue-400 hover:text-blue-300 transition-colors"
        >
          {copied ? <Check size={14} /> : <Copy size={14} />}
          {copied ? 'Copied' : 'Copy'}
        </button>
      </div>
      <pre className="p-4 overflow-x-auto text-sm font-mono text-emerald-400 leading-relaxed whitespace-pre">
        {content}
      </pre>
    </div>
  );
};

export default SysctlOutput;